# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scrollview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class ContactWidget(QtWidgets.QWidget):
    def __init__(self, contact, *args, **kwargs):
        super().__init__( *args, **kwargs)
        self.contact = contact
        self.layout = QtWidgets.QGridLayout()
        self.setLayout(self.layout)
        self.gridLayoutWidget = QtWidgets.QWidget()
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 50, 291, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView.setMaximumWidth(100)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        self.label_2 = QtWidgets.QLabel(f"Phone: {self.contact['phonenumber']}",self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        
        self.label_3 = QtWidgets.QLabel(f"Status: {self.contact['status']}",self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        
        self.label_3 = QtWidgets.QLabel(f"Data Set: {self.contact['status']}",self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        
        self.label = QtWidgets.QLabel(f"Name: {self.contact['name']}",self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        
        
        self.buttonLayout = QtWidgets.QHBoxLayout()

        self.infoButton = QtWidgets.QPushButton("INFO")
        self.infoButton.setObjectName("infoButton")
        self.infoButton.setMaximumWidth(50)
        self.buttonLayout.addWidget(self.infoButton)

        self.editButton = QtWidgets.QPushButton("EDIT")
        self.editButton.setObjectName("editButton")
        self.editButton.setMaximumWidth(50)
        self.buttonLayout.addWidget(self.editButton)
        
        self.deleteButton = QtWidgets.QPushButton("DELETE")
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.setMaximumWidth(75)
        self.buttonLayout.addWidget(self.deleteButton)

        self.gridLayout.addLayout(self.buttonLayout, 0, 2, 1, 1)

        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)

        self.layout.addWidget(self.gridLayoutWidget)

class ScrollView(QtWidgets.QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.layout = QtWidgets.QGridLayout()
        self.setLayout(self.layout)

        self.vbox = QtWidgets.QVBoxLayout()

        for i in range(1,50):
            contact = {f"name": f"Test {i}","phonenumber": "0000000000", "status": "Active", "last_modified": "04/20/2021"}
            self.vbox.addWidget(ContactWidget(contact))

        
        self.gridLayoutWidget = QtWidgets.QWidget()
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        self.scrollArea = QtWidgets.QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 377, 277))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setLayout(self.vbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        

        self.layout.addWidget(self.gridLayoutWidget)